let arr = [1,2,5,6,7]
// console.log(arr)
// console.log(arr.length)
// console.log(arr[4])
// console.log(arr.toString())
arr.pop()
console.log(arr)
arr.push(100)
console.log(arr)
console.log(arr.join(" and "))
arr.push("Harry")
console.log(arr)
arr.shift()
console.log(arr)
arr.unshift("Jack")
console.log(arr)    

arr.splice(1,3,263,3737)
console.log(arr)